name: fridgefinds
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.6

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/  # This ensures the fonts folder is recognized
    - assets/images/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700