// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiQJTUA6YdK0JA8xqyY9nI2dVzzBpAKk',
    appId: '1:530777094229:web:0a983e83465dfa1fff3cdc',
    messagingSenderId: '530777094229',
    projectId: 'fridgefinds-orion',
    authDomain: 'fridgefinds-orion.firebaseapp.com',
    databaseURL: 'https://fridgefinds-orion-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinds-orion.firebasestorage.app',
    measurementId: 'G-N2X94R702Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfbFbFrLUJo8F9NlNoNigeW1ejJEOJNPs',
    appId: '1:530777094229:android:c863c51ce62d92f7ff3cdc',
    messagingSenderId: '530777094229',
    projectId: 'fridgefinds-orion',
    databaseURL: 'https://fridgefinds-orion-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinds-orion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8eagMJCqLOMaWNOv3d3ynYsbN5Y-PVw',
    appId: '1:530777094229:ios:4f249e6eff17dee0ff3cdc',
    messagingSenderId: '530777094229',
    projectId: 'fridgefinds-orion',
    databaseURL: 'https://fridgefinds-orion-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinds-orion.firebasestorage.app',
    androidClientId: '530777094229-ts1meni4a3akl4bio7nldk7b0t06c6lu.apps.googleusercontent.com',
    iosClientId: '530777094229-pqvbd6hr0hr03fd2g771npfrgl03hf7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgeFinds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh8eagMJCqLOMaWNOv3d3ynYsbN5Y-PVw',
    appId: '1:530777094229:ios:4f249e6eff17dee0ff3cdc',
    messagingSenderId: '530777094229',
    projectId: 'fridgefinds-orion',
    databaseURL: 'https://fridgefinds-orion-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinds-orion.firebasestorage.app',
    androidClientId: '530777094229-ts1meni4a3akl4bio7nldk7b0t06c6lu.apps.googleusercontent.com',
    iosClientId: '530777094229-pqvbd6hr0hr03fd2g771npfrgl03hf7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.fridgeFinds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhiQJTUA6YdK0JA8xqyY9nI2dVzzBpAKk',
    appId: '1:530777094229:web:ddce89c9ef57a853ff3cdc',
    messagingSenderId: '530777094229',
    projectId: 'fridgefinds-orion',
    authDomain: 'fridgefinds-orion.firebaseapp.com',
    databaseURL: 'https://fridgefinds-orion-default-rtdb.firebaseio.com',
    storageBucket: 'fridgefinds-orion.firebasestorage.app',
    measurementId: 'G-D7WWXD3T1F',
  );

}